### ISSUE TITLE
Few of the wings 5-cycles are not center safe, and also unsolve the center

### ISSUE THREAD

**Issue by abunickabhi** [Roman-/comms#1]
For example, this commutator LBu-FLu-RDf-DLf-LUf.: [L, d' u f u' d] (in https://raw.githubusercontent.com/Roman-/comms/master/oneMovePartA_raw/w5cycles5moves.txt) also affects 2 +centers when executed on a solved cube, and makes the 2 +centers unsolved.

What could be the possible reason that the commutator unsolves the t-centers? If the reason is found, how to remove such cases from the generator?

**Comment by Roman-** [comment]
The most likely reason it happened was me being stupid and missing the "centres must be solved" criteria when generating wings 5cycles.
I will update them in a few days, thanks for noticing!

**Comment by Roman-** [comment]
Another reason might be that I did it intentionally as these commutators may be interpreted as wing 5cycles for 4x4 cube. This however contradicts the README where it's clearly stated that these algs are for 5x5 :D

I have completely updated the codebase for the project. I will consider more specific cases groups like "3cycles", "center-safe 3cycles", "center-safe 5cycles" etc, then upload new results

**Comment by abunickabhi** [comment]
Yes that can be the reason, many good wing algs on the 4x4, may influence +centers on 5x5. So then the debate is to whether maintain uniform algset for both 4x4 and 5x5, or generate different ones for 4x4, and a bit longer ones and +center safe for 5x5.

**Comment by Roman-** [comment]
Fixed by 2459530 (see the README note about centers safety)
